function m(b,a,c,d){b.j.pb(b.tb,a,c,d)}function n(b,a,c,d){b.j.ba?m(b,a,c,d):b.j.Te()._OnMessageFromDOM({type:"event",component:b.tb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function p(b,a,c){b.j.B(b.tb,a,c)}function v(b,a){for(const [c,d]of a)p(b,c,d)}function w(b){b.Yb||(b.j.Cc(b.je),b.Yb=!0)}window.wa=class{constructor(b,a){this.j=b;this.tb=a;this.Yb=!1;this.je=()=>this.Sa()}rc(){}Sa(){}};
window.Gf=class{constructor(){this.md=-1}l(){-1!==this.md&&(self.clearTimeout(this.md),this.md=-1)}};"use strict";function ba(b,a){p(b,"get-element",c=>{const d=x(b,c.elementId);return a(d,c)})}function x(b,a){b=b.Xa.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Wb}
window.td=class extends self.wa{constructor(b,a){super(b,a);this.Xa=new Map;this.rb=!0;v(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=x(this,c);this.rb&&d.parentElement.removeChild(d);this.Xa.delete(c)}],["set-visible",c=>{if(this.rb){var d=this.Xa.get(c.elementId),e=d.Wb;d.Td?e.style.display=c.isVisible?"":"none":d.mf=!!c.isVisible}}],["update-position",c=>{if(this.rb){var d=this.Xa.get(c.elementId),e=d.Wb,f=this.j;e.style.left=c.left+"px";e.style.top=
c.top+"px";e.style.width=c.width+"px";e.style.height=c.height+"px";var g=c.fontSize;null!==g&&(e.style.fontSize=g+"em");g=c.htmlIndex;d.sf=g;g=f.vd(g);g!==d.Ja&&(e.remove(),f.Lb(g).appendChild(e),d.Ja=g,f.Oc());c=c.htmlZIndex;c!==d.Wc&&(d.Wc=c,f.Oc());d.Td||(d.Td=!0,d.mf&&(e.style.display=""))}}],["update-state",c=>{x(this,c.elementId);throw Error("required override");}],["focus",c=>this.Lc(c)],["set-css-style",c=>{const d=x(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,
c):d.style[e]=c}],["set-attribute",c=>{x(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{x(this,c.elementId).removeAttribute(c.name)}]]);ba(this,c=>c)}Lc(b){var a=x(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const ca=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent),da=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ea=0;
function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.wf?new Promise(c=>{const d="c3_resolve_"+ea;++ea;self[d]=c;a.textContent=b.Af+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function fa(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let A=new Audio;
const ha={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ia(b){b=await ja(b);return(new TextDecoder("utf-8")).decode(b)}
function ja(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const B=[];let D=0;window.RealFile=window.File;const E=[],G=new Map,H=new Map;let ka=0;const la=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");la.push(b)};const ma=new Set(["cordova","playable-ad","instant-games"]);let qa=!1;
window.ga=class b{constructor(a){this.ba=a.Cf;this.za=null;this.aa="";this.fb=a.zf;this.Jb={};this.Za=this.va=null;this.Wa=[];this.na=null;this.Xd=!0;this.M=[];this.fd=[];this.gd=!1;this.ke=()=>this.Re();this.Yc=!1;this.Qd=0;this.yb=null;this.eb=-1;this.rf=()=>this.bf();this.Gb=new Set;this.nd=null;this.le=[];this.u=a.me;this.Zb="file"===location.protocol.substr(0,4);if("playable-ad"===this.u||"instant-games"===this.u)this.ba=!1;da&&(this.ba=!1);if("cordova"===this.u&&this.ba&&y){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ba=!1)}this.pa()?self.chrome.webview.addEventListener("message",c=>this.Fd(c.data)):"macos-wkwebview"===this.u&&(self.C3WrapperOnMessage=c=>this.Fd(c));this.bc=this.sa=null;"html5"!==this.u||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.ff(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.Xe());this.B("runtime","cordova-fetch-local-file",c=>this.Ye(c));this.B("runtime","create-job-worker",()=>this.Ze());this.B("runtime","send-wrapper-extension-message",c=>this.ef(c));"cordova"===this.u?document.addEventListener("deviceready",()=>this.Pb(a)):this.Pb(a)}l(){this.Dc();this.za&&(this.za=this.za.onmessage=null);this.va&&(this.va.terminate(),this.va=null);this.Za&&(this.Za.l(),this.Za=null);for(const {canvas:a,
ib:c}of this.M)a.remove(),c.remove();this.M.length=0}wd(){return this.M[0].canvas}vd(a){return Math.min(a,this.M.length-1)}Lb(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].ib}_GetHTMLWrapElement(a){return this.Lb(a)}He(){return ca&&"cordova"===this.u}nb(){const a=navigator.userAgent;return ca&&ma.has(this.u)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Fe(){return y}xd(){return y&&ma.has(this.u)}zd(){return"windows-webview2"===this.u||!!("preview"===
this.u&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}pa(){return this.zd()||"xbox-uwp-webview2"===this.u}async Pb(a){this.ba&&!await fa()&&(this.ba=!1);"macos-wkwebview"===this.u?this.Ha({type:"ready"}):this.pa()&&(this.hf(),this.le=(await this.We()).registeredComponentIds);if("playable-ad"===this.u){this.sa=self.c3_base64files;this.bc={};await this.Oe();for(let d=0,e=a.hb.length;d<e;++d){var c=a.hb[d];this.bc.hasOwnProperty(c)?a.hb[d]={wf:!0,Af:this.bc[c]}:this.sa.hasOwnProperty(c)&&
(a.hb[d]=URL.createObjectURL(this.sa[c]))}a.qc=[]}if("nwjs"===this.u&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Cc(()=>{d++;document.documentElement.style.opacity=0===d%2?"1":"0.999"})}a.yf?this.aa=a.yf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Ef&&(this.Jb=a.Ef);c=new MessageChannel;this.za=c.port1;this.za.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&
window.c3_addPortMessageHandler(d=>this.af(d));this.yb=new self.Ie(this);await ra(this.yb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ba?await this.Ve(a,c.port2):await this.Ue(a,c.port2)}Fc(a){a=this.Jb.hasOwnProperty(a)?this.Jb[a]:a.endsWith("/workermain.js")&&this.Jb.hasOwnProperty("workermain.js")?
this.Jb["workermain.js"]:"playable-ad"===this.u&&this.sa.hasOwnProperty(a)?this.sa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async tc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.u&&this.Zb)return a=await this.Kb(d.vf?a:this.fb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),
d)}return new Worker(a,d)}qa(){return Math.max(window.innerWidth,1)}ha(){return Math.max(window.innerHeight,1)}vc(){return this.pa()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.u)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}Dd(a){var c=this.aa,d=location.href,e=this.qa(),
f=this.ha(),g=this.vc(),h=window.devicePixelRatio,k=b.mb(),l=a.Kf,q=window.cr_previewImageBlobs||this.sa,r=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,u=window.cr_swClientId||"";a=a.me;var aa=(new URLSearchParams(self.location.search)).has("debug"),F=this.yb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,cssDisplayMode:g,devicePixelRatio:h,isFullscreen:k,projectData:l,previewImageBlobs:q,previewProjectFileBlobs:r,previewProjectFileSWUrls:t,swClientId:u,
exportType:a,isDebug:aa,ife:!!self.Jf,jobScheduler:{inputPort:F.Xc,outputPort:F.ed,maxNumWorkers:F.nf},supportedAudioFormats:ha,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.fb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.fb+"opus.wasm.wasm",isFileProtocol:this.Zb,isiOSCordova:this.He(),isiOSWebView:this.nb(),isWindowsWebView2:this.zd(),isAnyWebView2Wrapper:this.pa(),wrapperComponentIds:this.le,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ve(a,c){const d=
this.Fc(a.Df);"preview"===this.u?(this.va=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,q)=>{const r=t=>{this.va.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():q()};this.va.addEventListener("message",r);this.va.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.va=await this.tc(d,this.aa,{type:"module",name:"Runtime",vf:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();
document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,ib:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.qc||[],k=a.hb;h=await Promise.all(h.map(l=>this.Ta(l)));k=await Promise.all(k.map(l=>this.Ta(l)));if("cordova"===this.u)for(let l=0,q=a.pc.length;l<q;++l){const r=a.pc[l],t=r[0];if(t===a.od||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Ta(t)}this.va.postMessage(Object.assign(this.Dd(a),
{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.pc,mainProjectScript:a.od,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...sa(this.yb)]);this.Wa=E.map(l=>new l(this));this.Cd();ta(e);ua(g);va(this.na);self.c3_callFunction=(l,q)=>{var r=this.na;return r.j.Ad(r.tb,"js-invoke-function",{name:l,params:q})};"preview"===this.u&&(self.goToLastErrorScript=()=>this.pb("runtime","go-to-last-error-script"))}async Ue(a,c){const d=
document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,ib:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Wa=E.map(h=>new h(this));this.Cd();ta(d);ua(e);e=a.hb.map(h=>"string"===typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.qc)){var f=[...a.qc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=
await Promise.all(e.map(h=>this.Ta(h)));await Promise.all(e.map(h=>z(h)));e=self.C3_ProjectScriptsStatus;f=a.od;const g=a.pc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Ta(k),await z(k),"preview"!==this.u||e[h]||this.Hd(h,"main script did not run to completion")}catch(l){this.Hd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=await this.Ta(k),await z(k);"preview"===this.u&&"object"!==typeof self.Ff.Hf?(this.Rb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Dd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:la}),va(this.na),this.Ed(),this.Za=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Za,a))}Hd(a,c){this.Rb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ed(){this.Rb()}Rb(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Ze(){const a=await xa(this.yb);return{outputPort:a,transferables:[a]}}ff(a){if(!this.Yc){var c=a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,ib:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Xd&&(g.style.display="",h.style.display=
"");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Xd=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,ib:q}=this.M.pop();q.remove();this.ba&&!d?this.fd.push(l):l.remove()}else if(c>this.M.length)for(let l=0,q=c-this.M.length;l<q;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),
this.ba?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,ta(c),ua(d),this.M.push({canvas:c,ib:d});for(const l of this.Wa)if(l instanceof window.td&&l.rb)for(const q of l.Xa.values())e=l.j.vd(q.sf),f=q.Ja,-1!==
e&&-1!==f&&e!==f&&(f=q.Wb,f.remove(),l.j.Lb(e).appendChild(f),q.Ja=e);this.Oc();return{addedCanvases:a,transferables:k}}Xe(){for(const a of this.fd)a.remove();this.fd.length=0}Oc(){this.gd||(this.gd=!0,this.Cc(this.ke))}Re(){this.Gd(this.ke);this.gd=!1;let a=[];for(var c of this.Wa)if(c instanceof window.td){var d=c.rb?[...c.Xa.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.Ja,l=h.Ja;return k!==l?k-l:g.Wc-h.Wc});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.Ja!==c&&(this.Bd(c,a.slice(d,
e)),c=g.Ja,d=e)}d<e&&this.Bd(c,a.slice(d,e))}Bd(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.Wb);var d=new Set(c);a=this.Lb(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Te(){if(this.ba)throw Error("not available in worker mode");return this.Za}pb(a,c,d,e,f){this.za.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},
f)}Ad(a,c,d,e,f){const g=ka++,h=new Promise((k,l)=>{H.set(g,{resolve:k,reject:l})});this.za.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.$e(a);if("result"===c)this.cf(a);else if("runtime-ready"===c)this.df();else if("alert-error"===c)this.Rb(),alert(a.message);else if("creating-runtime"===c)this.Ed();else throw Error(`unknown message '${c}'`);}$e(a){const c=a.component,d=a.handler,
e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Qb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Qb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Qb(f,!1,""+h)}):this.Qb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Qb(a,c,d){let e;d&&d.transferables&&
(e=d.transferables);this.za.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}cf(a){const c=a.responseId,d=a.isOk;a=a.result;const e=H.get(c);d?e.resolve(a):e.reject(a);H.delete(c)}B(a,c,d){let e=G.get(a);e||(e=new Map,G.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Da(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}Cd(){for(const a of this.Wa)if("runtime"===a.tb){this.na=a;return}throw Error("cannot find runtime DOM handler");
}af(a){this.pb("debugger","message",a)}df(){for(const a of this.Wa)a.rc()}static mb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||qa)}static Sb(a){qa=!!a}Cc(a){this.Gb.add(a);this.Nc()}Gd(a){this.Gb.delete(a);0===this.Gb.size&&this.Dc()}Nc(){-1===this.eb&&0<this.Gb.size&&(this.eb=requestAnimationFrame(this.rf))}Dc(){-1!==this.eb&&(cancelAnimationFrame(this.eb),this.eb=-1)}bf(){this.eb=-1;for(const a of this.Gb)a();this.Nc()}Ga(a){this.na.Ga(a)}Ra(a){this.na.Ra(a)}Mc(){this.na.Mc()}Ob(a){this.na.Ob(a)}Ge(){return!!ha["audio/webm; codecs=opus"]}async jf(a){a=
await this.Ad("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Ke(a){this.Yc=!0;this.Qd=a}Ee(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}yd(a){return!this.Ee(a)}async Ta(a){return"cordova"===this.u&&(a.startsWith("file:")||this.Zb&&this.yd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Kb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ye(a){const c=a.filename;switch(a.as){case "text":return await this.De(c);
case "buffer":return await this.Kb(c);default:throw Error("unsupported type");}}sd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async De(a){a=await this.sd(a);return await ia(a)}Ec(){if(B.length&&!(8<=D)){D++;var a=B.shift();this.Pe(a.filename,a.Bf,a.uf)}}Kb(a){return new Promise((c,d)=>{B.push({filename:a,Bf:e=>{D--;this.Ec();c(e)},uf:e=>{D--;this.Ec();d(e)}});this.Ec()})}async Pe(a,c,d){try{const e=
await this.sd(a),f=await ja(e);c(f)}catch(e){d(e)}}Fd(a){if("entered-fullscreen"===a)b.Sb(!0),I(this.na);else if("exited-fullscreen"===a)b.Sb(!1),I(this.na);else if("object"===typeof a){const c=a.type;"directory-handles"!==c&&("wrapper-init-response"===c?(this.nd(a),this.nd=null):"extension-message"===c?this.pb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a))}else console.warn("Unknown wrapper message: ",a)}ef(a){this.Ha({type:"extension-message",componentId:a.componentId,
messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}Ha(a){this.pa()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.u&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}hf(){window.moveTo=(a,c)=>{this.Ha({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.Ha({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}We(){return this.pa()?new Promise(a=>{this.nd=a;this.Ha({type:"wrapper-init"})}):
Promise.resolve()}async Oe(){const a=[];for(const [c,d]of Object.entries(this.sa))a.push(this.Ne(c,d));await Promise.all(a)}async Ne(a,c){if("object"===typeof c)this.sa[a]=new Blob([c.str],{type:c.type}),this.bc[a]=c.str;else{let d=await this.Se(c);d||(d=this.Qe(c));this.sa[a]=d}}async Se(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}Qe(a){a=this.gf(a);return this.Me(a.data,a.xf)}gf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{xf:a,data:d}}Me(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const J=self.ga,ya=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},za={dispatchUserScriptEvent:!0},Aa={dispatchRuntimeEvent:!0};function Ba(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}
function Ca(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function Da(b){b=URL.createObjectURL(b);try{return await Ca(b)}finally{URL.revokeObjectURL(b)}}function Ea(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Fa=new Set(["input","textarea","datalist","select"]),Ga=new Set(["canvas","body","html"]);
function L(b){b.target.tagName&&Ga.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ha(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Ia(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await Da(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Da(b);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ja=!1;document.addEventListener("pause",()=>Ja=!0);document.addEventListener("resume",()=>Ja=!1);function ta(b){b.addEventListener("selectstart",L);b.addEventListener("gesturehold",L);b.addEventListener("pointerdown",L)}function ua(b){b.addEventListener("selectstart",Ha);b.addEventListener("gesturehold",Ha);b.addEventListener("touchstart",Ha)}function va(b){b.Pd=!0;b.ad=b.j.qa();b.zb=b.j.ha()}
function I(b){if(!b.la){var a=J.mb();a&&"any"!==b.kd&&Ka(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.qa(),innerHeight:b.ha()})}}async function La(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ma(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Na(b){return await self.C3_GetSvgImageSize(b.blob)}function Oa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Pa(b){self.setTimeout(()=>{b.Od=!0},1E3);"cordova"===b.j.u?(document.addEventListener("pause",()=>Qa(b,!0)),document.addEventListener("resume",()=>Qa(b,!1))):document.addEventListener("visibilitychange",()=>Qa(b,"hidden"===document.visibilityState));b.fc=!("hidden"!==document.visibilityState&&!Ja);return{isSuspended:b.fc}}
function Ra(b){b.Jd||(b.Jd=!0,window.addEventListener("deviceorientation",a=>{b.la||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{b.la||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Sa(b){b.Id||(b.Id=!0,window.addEventListener("devicemotion",a=>{if(!b.la){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Ta(b){await Ba(b.url)}
function Ua(b,a){b.Rd=a.message;-1===b.Sc&&(b.Sc=setTimeout(()=>{b.Sc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Rd)},250))}function Va(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:J.mb(),innerWidth:b.qa(),innerHeight:b.ha()})}
function Qa(b,a){b.fc!==a&&((b.fc=a)?b.j.Dc():b.j.Nc(),m(b,"visibilitychange",{hidden:a}),!a&&b.j.nb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function Wa(b,a,c){"Backspace"===c.key&&L(c);"nwjs"===b.j.u&&"u"===c.key&&(c.ctrlKey||c.metaKey)&&c.preventDefault();if(!b.la){var d=ya.get(c.code)||c.code;n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},K)}}
function M(b,a,c,d){b.la||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Ca,pageX:c.pageX,pageY:c.pageY+b.Ca,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function N(b,a,c){if(!b.la){var d=0;"mouse"===c.pointerType&&(d=b.cd);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Ca,pageX:c.pageX,pageY:c.pageY+b.Ca,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},K);"mouse"===c.pointerType&&
(b.cd=c.buttons)}}function Xa(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Ca=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Ca=a))}}
function Ya(b,a,c,d){const e=b.qa(),f=b.ha();b.gb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.mb(),cssDisplayMode:b.j.vc()}):10>d&&Za(b,e,f,d+1)}function Za(b,a,c,d){-1!==b.gb&&clearTimeout(b.gb);b.gb=setTimeout(()=>Ya(b,a,c,d),48)}
function Ka(b){b=b.kd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function $a(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.Da(class extends self.wa{constructor(b){super(b,"runtime");this.Pd=!1;this.gb=-1;this.kd="any";this.fc=this.Id=this.Jd=!1;this.mc=document.createElement("div");this.mc.className="c3-screen-reader-text";this.mc.setAttribute("aria-live","polite");document.body.appendChild(this.mc);this.La=null;this.la=!1;this.Rd="";this.Sc=-1;this.Od=!1;this.ad=b.qa();this.zb=b.ha();this.Ca=this.Ib=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>La(c));b.B("runtime","raster-svg-image",c=>Ma(c));b.B("runtime","get-svg-image-size",c=>Na(c));b.B("runtime","set-target-orientation",c=>{this.kd=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Oa(c));b.B("runtime","go-to-script",c=>Oa(c));b.B("runtime","before-start-ticking",()=>Pa(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.La||(this.La=document.createElement("div"),this.La.id="inspectOutline",document.body.appendChild(this.La));var d=this.La;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.La&&(this.La.style.display="none")});b.B("runtime","enable-device-orientation",()=>Ra(this));b.B("runtime","enable-device-motion",()=>Sa(this));b.B("runtime","add-stylesheet",c=>Ta(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>this.Ic(c));b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.mc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===d?
(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.la=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.j.wd().style.display="";this.j.Ke(c.duration)});b.B("runtime","export-to-video-progress",c=>Ua(this,c));b.B("runtime","exported-to-video",c=>{window.tf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.tf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ea(d)||c.preventDefault()});window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);window.addEventListener("touchstart",L,{passive:!1});window.addEventListener("pointerdown",L,{passive:!1});this.cd=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Ia,{passive:!1});window.addEventListener("wheel",Ia,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.la&&this.Pd){var c=this.qa();var d=this.ha();if(this.j.xd()){if(this.Od){if(this.ad===
c&&d<this.zb){this.Ib=this.zb-d;Xa(this,this.zb,this.Ib);c=void 0;break a}0<this.Ib&&(this.Ib=0,Xa(this,d,this.Ib))}this.ad=c;this.zb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.mb(),cssDisplayMode:this.j.vc()});this.j.nb()&&(-1!==this.gb&&clearTimeout(this.gb),Ya(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>I(this));window.addEventListener("webkitfullscreenchange",()=>I(this));window.addEventListener("mozfullscreenchange",
()=>I(this));window.addEventListener("fullscreenerror",c=>Va(this,c));window.addEventListener("webkitfullscreenerror",c=>Va(this,c));window.addEventListener("mozfullscreenerror",c=>Va(this,c));if(b.nb()){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d});document.documentElement.setAttribute("ioswebview","")}this.$a=new Set;this.dc=new WeakSet;this.ya=!1}rc(){window.addEventListener("focus",
()=>{m(this,"window-focus",null,Aa)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}m(this,"window-blur",{parentHasFocus:a},Aa);this.cd=0});window.addEventListener("focusin",a=>{a=a.target;(Fa.has(a.tagName.toLowerCase())||Ea(a))&&m(this,"keyboard-blur",null,Aa)});window.addEventListener("keydown",a=>Wa(this,"keydown",a));window.addEventListener("keyup",a=>Wa(this,"keyup",a));window.addEventListener("mousedown",a=>M(this,"mousedown",a,
za));window.addEventListener("mousemove",a=>M(this,"mousemove",a,za));window.addEventListener("mouseup",a=>M(this,"mouseup",a,za));window.addEventListener("dblclick",a=>M(this,"dblclick",a,K));window.addEventListener("wheel",a=>{this.la||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Ca,pageX:a.pageX,pageY:a.pageY+this.Ca,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();
$a(a.target)&&document.activeElement&&!$a(document.activeElement)&&document.activeElement.blur();N(this,"pointerdown",a)});this.j.ba&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{N(this,"pointermove",a)}):window.addEventListener("pointermove",a=>N(this,"pointermove",a));window.addEventListener("pointerup",a=>N(this,"pointerup",a));window.addEventListener("pointercancel",a=>N(this,"pointercancel",a));const b=()=>this.Mc();window.addEventListener("pointerup",
b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.j.Fe()&&!this.j.xd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Xa(this,this.ha(),navigator.virtualKeyboard.boundingRect.height)}));this.j.nb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}qa(){return this.j.qa()}ha(){return this.j.ha()}Mc(){var b=
[...this.$a];this.$a.clear();if(!this.ya)for(const a of b)(b=a.play())&&b.catch(()=>{this.dc.has(a)||this.$a.add(a)})}Ga(b){if("function"!==typeof b.play)throw Error("missing play function");this.dc.delete(b);let a;try{a=b.play()}catch(c){this.$a.add(b);return}a&&a.catch(()=>{this.dc.has(b)||this.$a.add(b)})}Ra(b){this.$a.delete(b);this.dc.add(b)}Ob(b){this.ya=!!b}Ic(b){alert(b.message)}});"use strict";
async function ra(b){if(b.kf)throw Error("already initialised");b.kf=!0;var a=b.Aa.Fc(("playable-ad"===b.Aa.u?b.Aa.fb:"")+"dispatchworker.js");b.Rc=await b.Aa.tc(a,b.sb,{name:"DispatchWorker"});a=new MessageChannel;b.Xc=a.port1;b.Rc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.ed=await xa(b)}function sa(b){return[b.Xc,b.ed]}
async function xa(b){const a=b.Yd.length;var c=b.Aa.Fc(("playable-ad"===b.Aa.u?b.Aa.fb:"")+"jobworker.js");c=await b.Aa.tc(c,b.sb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Rc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Yd.push(c);return e.port1}
self.Ie=class{constructor(b){this.Aa=b;this.sb=b.aa;this.sb="preview"===b.u?this.sb+"workers/":this.sb+b.fb;this.nf=Math.min(navigator.hardwareConcurrency||2,16);this.Rc=null;this.Yd=[];this.ed=this.Xc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.ga({Cf:!1,Df:"workermain.js",hb:["scripts/c3runtime.js"],pc:[],od:"",zf:"scripts/",qc:[],me:"html5"}));"use strict";
async function ab(){try{return{isOk:!0,isPersistent:await navigator.storage.persist()}}catch(b){return console.error("[Construct] Error requesting persistent storage: ",b),{isOk:!1}}}self.ga.Da(class extends self.wa{constructor(b){super(b,"localstorage");v(this,[["init",()=>this.Pb()],["request-persistent",()=>ab()]])}async Pb(){let b=!1;try{b=await navigator.storage.persisted()}catch(a){b=!1,console.warn("[Construct] Error checking storage persisted state: ",a)}return{isPersistent:b}}});"use strict";
async function bb(b,a){a=a.type;let c=!0;0===a?c=await cb():1===a&&(c=await db());m(b,"permission-result",{type:a,result:c})}async function cb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function db(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.ga.Da(class extends self.wa{constructor(b){super(b,"touch");p(this,"request-permission",a=>bb(this,a))}});"use strict";
self.ga.Da(class extends self.wa{constructor(b){super(b,"mouse");v(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.j.wd().requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";let O=null,eb=null;window.addEventListener("beforeinstallprompt",b=>{b.preventDefault();O=b;eb&&m(eb,"install-available");return!1});function fb(){}function gb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(b,"sw-message",a.data))}
function hb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}async function ib(){if(!O)return{result:"unavailable"};try{return O.prompt(),{result:(await O.userChoice).outcome}}catch(b){return console.error("[Construct] Requesting install failed: ",b),{result:"failed"}}}
self.ga.Da(class extends self.wa{constructor(b){super(b,"browser");this.u="";v(this,[["get-initial-state",a=>this.Kc(a)],["ready-for-sw-messages",()=>gb(this)],["alert",a=>this.Ic(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Lc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>hb(a)],["unlock-orientation",()=>{try{screen.orientation&&
screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();
else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===a||this.j.pa()?window.open(c,"_blank"):this.If||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.j.pa()||"macos-wkwebview"===this.u)self.ga.Sb(!0),
this.j.Ha({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof
Promise&&d.catch(fb)}}],["exit-fullscreen",()=>{if(this.j.pa()||"macos-wkwebview"===this.u)self.ga.Sb(!1),this.j.Ha({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(fb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",
a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:
{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}],["set-window-size",a=>{window.resizeTo(a.windowWidth,a.windowHeight)}],["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}],["request-install",()=>ib()],["set-warn-on-close",a=>{a.enabled?window.addEventListener("beforeunload",this.Kd):window.removeEventListener("beforeunload",this.Kd)}]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",
()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});this.Kd=a=>a.preventDefault();document.addEventListener("backbutton",()=>{m(this,"backbutton")})}rc(){O?m(this,"install-available"):eb=this;window.addEventListener("appinstalled",()=>{m(this,"app-installed")})}Kc(b){this.u=b.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,
screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}Ic(b){alert(b.message)}Lc(b){b=b.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";const kb=180/Math.PI;
async function lb(b,a){a.usePlayMusicAsSoundWorkaround&&(b.ic=!0);b.ld=a.timeScaleMode;b.ce=["equalpower","HRTF","soundfield"][a.panningModel];b.Nd=["linear","inverse","exponential"][a.distanceModel];b.de=a.refDistance;b.be=a.maxDistance;b.fe=a.rolloffFactor;if(b.j.Yc)b.ic=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.j.Qd)});else{var c={latencyHint:a.latencyHint};b.ie||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");mb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&mb(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Va=b.g.createGain();b.Va.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ca);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function nb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,q=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.Zd=g.slice(0);ob(b,g);try{b.R=await pb(b,c,d,e,g,f);if(q){Q(b.R,!0);var u=b.R,aa=q.x,F=q.y,Eb=q.z,Fb=q.angle,na=q.innerAngle,oa=q.outerAngle,pa=q.outerGain;if(u.xb){qb(u,aa,F,Eb,Fb);var C=self.jb.Le;
u.ta[0]!==C(na)&&(u.ta[0]=C(na),u.F.coneInnerAngle=C(na));u.ta[1]!==C(oa)&&(u.ta[1]=C(oa),u.F.coneOuterAngle=C(oa));u.ta[2]!==pa&&(u.ta[2]=pa,u.F.coneOuterGain=pa)}q.hasOwnProperty("uid")&&(b.R.ra=q.uid)}else"number"===typeof r&&0!==r?(R(b.R,!0),rb(b.R,r)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,k,l,t)}catch(Gb){console.error("[Construct] Audio: error starting playback: ",Gb);return}finally{c=g.join(" ");d=b.Fb.get(c);if(!d)throw Error("expected pending tag");d.pd--;0===d.pd&&(d.resolve(),b.Fb.delete(c))}w(b)}
async function sb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await tb(b,c);for(const h of S(b,c))if(!h.xa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.v.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Pa=d;h.Ya=g;h.he=a}T(b)}async function ub(b,a){const c=a.tags;a=a.rate;await tb(b,c);for(const d of S(b,c))d.ma!==a&&(d.ma=a,d.Ia())}async function vb(b,a){const c=a.tags;a=a.pos;await tb(b,c);for(const d of S(b,c))d.zc(a)}
async function wb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await pb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function xb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.l(),a=b.ja.indexOf(a),-1!==a&&b.ja.splice(a,1)}
async function yb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.se(b,...e);else if("delay"===c)d=new self.qe(b,...e);else if("convolution"===c){var g=d=new self.pe(b,f.ia,...e),h=a.bufferType;g.Ld=a.bufferOriginalUrl;g.Md=h}else if("flanger"===c)d=
new self.te(b,...e);else if("phaser"===c)d=new self.ve(b,...e);else if("gain"===c)d=new self.ue(b,...e);else if("stereopan"===c)d=new self.xe(b,...e);else if("tremolo"===c)d=new self.ye(b,...e);else if("ringmod"===c)d=new self.we(b,...e);else if("distortion"===c)d=new self.re(b,...e);else if("compressor"===c)d=new self.oe(b,...e);else if("analyser"===c)d=new self.ne(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ka.get(h);l||(l=[],g.ka.set(h,l));d.Wd=l.length;d.jd=
h;l.push(d);zb(g,h)}Ab(b)}
async function Bb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ea()&&1===c||!e.Ea()&&2===c?d.push(e):e.l();b.H=d}for(const f of b.ka.values())for(const g of f)g.l();b.ka.clear();b.nc=a.timeScale;b.Tc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ca[e]=d[e];b.g.listener.setOrientation(...b.ca)}b.ya=a.isSilent;b.j.Ob(b.ya);b.cc=a.masterVolume;b.Va.gain.value=
b.cc;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>yb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Cb(b,f,c)));T(b)}
async function Db(b,a){try{const c=b.g.suspend(a.time);b.Vd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.j.pb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Hb(d)),b.Vd=!0);await c}catch(c){Hb(c)}}
function mb(b){b.Xb||(b.Vc=!1,window.addEventListener("pointerup",b.Ba,!0),window.addEventListener("touchend",b.Ba,!0),window.addEventListener("click",b.Ba,!0),window.addEventListener("keydown",b.Ba,!0),b.Xb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ja)if(g.lb()===c)return await Ib(g),g;if(f)return null;if(e&&(b.ic||b.Ud)){f=0;for(let h=0,k=b.ja.length;h<k;++h)g=b.ja[h],b.ja[f]=g,g.Ea()?g.l():++f;b.ja.length=f}f="audio/webm; codecs=opus"===d&&!b.ie;e&&f&&(b.Ud=!0);c=!e||b.ic||f?new self.Be(b,a,c,d,e,f):new self.ze(b,a,c,d,e);b.ja.push(c);await Ib(c);b.ae.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.fa()}),b.ae.add(a));return c}
function Jb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Kb(b,a){return(a=b.ka.get(a.toLowerCase()))?a[0].N():b.ea()}function zb(b,a){a=a.toLowerCase();let c=b.ea();var d=b.ka.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ea()):e.U(d[f+1].N())}}for(const f of Lb(b,a))e=f,d=c,e=e.da||e.F||e.G,e.disconnect(),e.connect(d);b.Ma&&b.bd===a&&(b.Ma.disconnect(),b.Ma.connect(c))}
function*Lb(b,a){if(a)for(const c of b.H)Jb(0<c.oa.length?c.oa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Mb(b,a,c){return c?b.j.jf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Nb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.l():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.oa;var c=a;for(const e of c){c=!1;for(const f of b)if(Jb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function pb(b,a,c,d,e,f){for(const g of b.H)if(g.lb()===c&&(g.sc()||f))return g.oa=e,g;a=await P(b,a,c,d,f);e="html5"===a.Pc?new self.Ae(a.v,a,e):new self.Ce(a.v,a,e);b.H.push(e);return e}
function ob(b,a){a=a.join(" ");let c=b.Fb.get(a);if(!c){let d=null;c={pd:0,promise:new Promise(e=>d=e),resolve:d};b.Fb.set(a,c)}c.pd++}function tb(b,a){return(b=b.Fb.get((0===a.length?b.Zd:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Ua.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Ob(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function Ab(b){b.Zc||(b.Zc=!0,Promise.resolve().then(()=>Pb(b)))}
function Pb(b){const a={};for(const [c,d]of b.ka)a[c]=d.map(e=>e.kb());m(b,"fxstate",{fxstate:a});b.Zc=!1}
async function Cb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await pb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.bb[0]=f[0],b.bb[1]=f[1],b.bb[2]=f[2],f=d.orient,b.ab[0]=f[0],b.ab[1]=f[1],b.ab[2]=f[2],e.setPosition(...b.bb),e.setOrientation(...b.ab),b.ta[0]=d.cia,b.ta[1]=d.coa,b.ta[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.ra=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),rb(b,d));c.Play(k,l,q,0);a.isPlaying||c.ob();c.Hc(a)}}}function Hb(b){console.error("[Audio] Offline rendering error: ",b)}
self.jb=class extends self.wa{constructor(b){super(b,"audio");this.Va=this.g=null;this.Xb=this.Vc=!1;this.Ba=()=>{if(!this.Vc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Xb&&(this.Vc=!0,window.removeEventListener("pointerup",this.Ba,!0),window.removeEventListener("touchend",this.Ba,!0),window.removeEventListener("click",this.Ba,!0),window.removeEventListener("keydown",
this.Ba,!0),this.Xb=!1)}};this.ja=[];this.H=[];this.R=null;this.Zd=[];this.ae=new Set;this.$d=-1;this.Fb=new Map;this.cc=1;this.ya=!1;this.ld=0;this.nc=1;this.Tc=0;this.ce="HRTF";this.Nd="inverse";this.de=600;this.be=1E4;this.fe=1;this.$=[0,0,0];this.ca=[0,0,-1,0,1,0];this.Ud=this.ic=!1;this.ie=this.j.Ge();this.ka=new Map;this.Ua=new Set;this.Vd=this.Zc=!1;this.bd="";this.Ma=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ma&&this.Ma.disconnect();this.bd=c.toLowerCase();this.Ma=this.g.createMediaStreamSource(a);
this.Ma.connect(Kb(this,this.bd))};this.Vb=null;self.C3Audio_GetOutputStream=()=>{this.Vb||(this.Vb=this.g.createMediaStreamDestination(),this.Va.connect(this.Vb));return this.Vb.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>lb(this,a)],["play",a=>nb(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Fa()}],["stop-all",()=>{for(const a of this.H)a.Fa()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.ob():d.Nb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>sb(this,a)],["set-master-volume",a=>{this.cc=a.vol;this.Va.gain.value=this.cc}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Qb(d,a)}],["set-silent",a=>{this.ya=a.isSilent;this.j.Ob(this.ya);for(const c of this.H)c.Tb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.Ac(a)}],["set-playback-rate",a=>ub(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),rb(d,a)}],["seek",a=>vb(this,a)],["preload",a=>wb(this,a)],["unload",a=>xb(this,a)],["unload-all",()=>{for(const a of this.ja)a.l();this.ja.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.Bc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>yb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ka.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);Ab(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ka.get(a);if(!d||!d.length)break;for(const e of d)e.l();this.ka.delete(a);zb(this,a)}}],["tick",a=>{this.nc=a.timeScale;this.Tc=a.gameTime;this.$d=a.tickCount;if(0!==this.ld)for(var c of this.H)c.Ia();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ca[0]!==
c[0]||this.ca[1]!==c[1]||this.ca[2]!==c[2]||this.ca[3]!==c[3]||this.ca[4]!==c[4]||this.ca[5]!==c[5])){for(let d=0;6>d;++d)this.ca[d]=c[d];this.g.listener.setOrientation(...this.ca)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.ra===a&&qb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Bb(this,a)],["offline-render-audio",a=>Db(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ea(){return this.Va}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ea()}Mb(){return this.ya}Ga(b){this.j.Ga(b)}Ra(b){this.j.Ra(b)}Sa(){for(var b of this.Ua)b.Sa();
b=this.g.currentTime;for(var a of this.H)a.Sa(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.kb());m(this,"state",{tickCount:this.$d,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ua].map(c=>({tag:c.jd,index:c.Wd,peak:c.cb,rms:c.ee,binCount:c.m.frequencyBinCount,freqBins:c.Sd}))});0===a.length&&0===this.Ua.size&&this.Yb&&(this.j.Gd(this.je),this.Yb=!1)}static Le(b){return b*kb}static ud(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Je(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.ga.Da(self.jb);"use strict";function Ib(b){b.ac||(b.ac=b.Gc());return b.ac}self.qd=class{constructor(b,a,c,d,e){this.v=b;this.qf=a;this.Oa=c;this.T=d;this.lf=e;this.Pc="";this.ac=null}l(){this.ac=this.v=null}Gc(){}V(){return this.v.V()}wc(){return this.qf}lb(){return this.Oa}uc(){return this.T}Ea(){return this.lf}fa(){}};"use strict";
self.ze=class extends self.qd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Pc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.Ab=this.Bb=null;this.L.addEventListener("canplaythrough",()=>!0);this.Eb=this.V().createGain();this.Db=null;this.L.addEventListener("canplay",()=>{this.Bb&&(this.Bb(),this.Ab=this.Bb=null);!this.Db&&this.L&&(this.Db=this.V().createMediaElementSource(this.L),this.Db.connect(this.Eb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Oa}' error: `,f);this.Ab&&(this.Ab(f),this.Ab=this.Bb=null)})}l(){Nb(this.v,this);this.Eb.disconnect();this.Eb=null;this.Db.disconnect();this.Db=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.l()}Gc(){return new Promise((b,a)=>{this.Bb=b;this.Ab=a;this.L.src=this.Oa})}W(){return this.L}fa(){return this.L.duration}};"use strict";
async function Rb(b){if(b.Ka)return b.Ka;var a=b.v.j;if("cordova"===a.u&&a.yd(b.Oa)&&a.Zb)b.Ka=await a.Kb(b.Oa);else{a=await fetch(b.Oa);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ka=await a.arrayBuffer()}}async function Sb(b){if(b.ia)return b.ia;b.ia=await Mb(b.v,b.Ka,b.pf);b.Ka=null}
self.Be=class extends self.qd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Pc="webaudio";this.ia=this.Ka=null;this.pf=!!f}l(){Nb(this.v,this);this.ia=this.Ka=null;super.l()}async Gc(){try{await Rb(this),await Sb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Oa}': `,b)}}fa(){return this.ia?this.ia.duration:0}};"use strict";let Tb=0;
function Q(b,a){a=!!a;b.xb!==a&&(b.xb=a,b.xb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.v.ce,b.F.distanceModel=b.v.Nd,b.F.refDistance=b.v.de,b.F.maxDistance=b.v.be,b.F.rolloffFactor=b.v.fe),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ea())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ea())))}
function R(b,a){a=!!a;b.$b!==a&&(b.$b=a,b.$b?(Q(b,!1),b.da=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.da),b.da.connect(b.ea())):(b.da.disconnect(),b.da=null,b.G.disconnect(),b.G.connect(b.ea())))}function rb(b,a){b.$b&&b.hd!==a&&(b.da.pan.value=a,b.hd=a)}function U(b,a){b.Pa=a;b.G.gain.cancelScheduledValues(0);b.Ya=-1;b.G.gain.value=b.xc()}function Qb(b,a){a=!!a;b.xa!==a&&(b.xa=a,b.Tb())}
function qb(b,a,c,d,e){if(b.xb){var f=b.bb,g=b.ab,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.$c?b.v.Tc:performance.now()/1E3}
self.rd=class{constructor(b,a,c){this.v=b;this.P=a;this.oa=c;this.Ub=Tb++;this.G=this.V().createGain();this.G.connect(this.ea());this.F=null;this.xb=!1;this.bb=[0,0,0];this.ab=[0,0,0];this.ta=[0,0,0];this.da=null;this.$b=!1;this.hd=0;this.I=!0;this.Y=this.ua=this.J=!1;this.Pa=1;this.xa=!1;this.ma=1;b=this.v.ld;this.$c=1===b&&!this.Ea()||2===b;this.Ya=this.ra=-1;this.he=!1}l(){this.P=this.v=null;this.F&&(this.F.disconnect(),this.F=null);this.da&&(this.da.disconnect(),this.da=null);this.G.disconnect();
this.G=null}V(){return this.v.V()}ea(){return Kb(this.v,0<this.oa.length?this.oa[0]:"")}wc(){return this.P.wc()}lb(){return this.P.lb()}uc(){return this.P.uc()}Ea(){return this.P.Ea()}O(){}sc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Qa(){}fa(){return this.P.fa()}Play(){}Fa(){}ob(){}Nb(){}Sa(b){-1!==this.Ya&&b>=this.Ya&&(this.Ya=-1,this.he&&this.Fa(),Ob(this.v,"fade-ended",this.oa,this.Ub))}xc(){const b=this.Pa;return isFinite(b)?b:0}Mb(){return this.v.Mb()}Tb(){}Ac(){}Ia(){}zc(){}Bc(){}yc(){}kb(){var b=
this.Ub,a=this.oa,c=this.fa(),d=-1===this.Ya?this.Pa:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.bb,orient:this.ab,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ra}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Qa(),playbackRate:this.ma,uid:this.ra,bufferOriginalUrl:this.wc(),bufferUrl:"",bufferType:this.uc(),isMusic:this.Ea(),isLooping:this.Y,isMuted:this.xa,resumePosition:this.yc(),pan:f,stereoPan:this.da?
this.hd:null}}Hc(b){var a=b.playbackRate;this.ma!==a&&(this.ma=a,this.Ia());Qb(this,b.isMuted)}};"use strict";
self.Ae=class extends self.rd{constructor(b,a,c){super(b,a,c);this.P.Eb.connect(this.G);this.P.onended=()=>this.Jc()}l(){this.Fa();this.P.Eb.disconnect();super.l()}W(){return this.P.W()}Jc(){this.I=!0;this.ra=-1;Ob(this.v,"ended",this.oa,this.Ub)}O(){return this.W().ended}sc(){return this.I?!0:this.O()}Qa(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.fa()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);this.xa=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.lb()}' to position '${c}': `,e)}this.v.Ga(d);this.J=this.I=!1;this.Y=b;this.ma=1}Fa(){const b=this.W();b.paused||b.pause();this.v.Ra(b);this.I=!0;this.J=!1;this.ra=-1}ob(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.v.Ra(b);this.J=!0}}Nb(){!this.J||this.I||this.O()||(this.v.Ga(this.W()),this.J=!1)}Tb(){this.W().muted=this.xa||this.Mb()}Ac(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ia(){let b=this.ma;this.$c&&(b*=this.v.nc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}zc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}yc(){return this.Qa()}Bc(b){b?this.IsPlaying()?(this.W().pause(),this.ua=!0):this.ua=!1:this.ua&&(this.v.Ga(this.W()),this.ua=!1)}};"use strict";
function W(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.qb=null}
self.Ce=class extends self.rd{constructor(b,a,c){super(b,a,c);this.s=null;this.ec=d=>this.Jc(d);this.Uc=!0;this.qb=null;this.S=this.hc=this.jc=0;this.dd=1}l(){this.Fa();W(this);this.ec=null;super.l()}Jc(b){this.J||this.ua||b.target!==this.qb||(this.I=this.Uc=!0,this.ra=-1,W(this),Ob(this.v,"ended",this.oa,this.Ub))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Uc}sc(){return!this.s||this.I?!0:this.O()}Qa(){let b;b=this.J?this.S:this.hc+(V(this)-this.jc)*this.ma;this.Y||(b=Math.min(b,this.fa()));
return b}Play(b,a,c,d){this.xa=!1;this.dd=1;U(this,a);W(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ia;this.s.connect(this.G);this.qb=this.s;this.s.onended=this.ec;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Uc=!1;this.Y=b;this.ma=1;this.jc=V(this);this.hc=c}Fa(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.ra=-1}ob(){this.J||this.I||this.O()||(this.S=this.Qa(),this.Y&&(this.S%=this.fa()),this.J=!0,this.s.stop(0))}Nb(){!this.J||this.I||this.O()||(W(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ia,this.s.connect(this.G),this.qb=this.s,this.s.onended=this.ec,this.s.loop=this.Y,U(this,this.Pa),this.Ia(),this.s.start(0,this.S),this.jc=V(this),this.hc=this.S,this.J=!1)}xc(){return super.xc()*this.dd}Tb(){this.dd=this.xa||this.Mb()?0:1;U(this,this.Pa)}Ac(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ia(){let b=this.ma;this.$c&&(b*=this.v.nc);this.s&&(this.s.playbackRate.value=b)}zc(b){this.I||this.O()||(this.J?this.S=b:(this.ob(),
this.S=b,this.Nb()))}yc(){return this.S}Bc(b){b?this.IsPlaying()?(this.ua=!0,this.S=this.Qa(),this.Y&&(this.S%=this.fa()),this.s.stop(0)):this.ua=!1:this.ua&&(W(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ia,this.s.connect(this.G),this.qb=this.s,this.s.onended=this.ec,this.s.loop=this.Y,U(this,this.Pa),this.Ia(),this.s.start(0,this.S),this.jc=V(this),this.hc=this.S,this.ua=!1)}Hc(b){super.Hc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.v=b;this.g=b.V();this.Wd=-1;this.T=this.jd="";this.o=null}l(){this.g=null}N(){}U(){}kb(){return{type:this.T,tag:this.jd,params:this.o}}}
self.se=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.A=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}l(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.qe=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.Cb=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.vb=X(this);this.vb.gain.value=c;this.A.connect(this.Cb);this.A.connect(this.h);this.Cb.connect(this.i);this.Cb.connect(this.X);this.X.connect(this.vb);this.vb.connect(this.Cb)}l(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.Cb.disconnect();
this.X.disconnect();this.vb.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.jb.ud;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);Y(this,this.vb.gain,e(a),c,d);break;case 5:this.o[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.pe=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Md=this.Ld="";this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.ub=this.g.createConvolver();this.ub.normalize=c;this.ub.buffer=a;this.A.connect(this.ub);this.A.connect(this.h);this.ub.connect(this.i)}l(){this.A.disconnect();this.ub.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}kb(){const b=super.kb();b.bufferOriginalUrl=this.Ld;b.bufferUrl="";b.bufferType=this.Md;return b}};
self.te=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.A=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.wb=X(this);this.wb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=X(this);this.K.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.wb);this.wb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.wb.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;Y(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;Y(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,Y(this,this.wb.gain,a/100,c,d)}}};
self.ve=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.A=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=X(this);this.K.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;Y(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,Y(this,this.C.frequency,a,c,d)}}};self.ue=class extends Z{constructor(b,a){super(b);this.T="gain";this.o=[a];this.m=X(this);this.m.gain.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){const e=self.jb.ud;switch(b){case 4:this.o[0]=e(a),Y(this,this.m.gain,e(a),c,d)}}};
self.xe=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.m=this.g.createStereoPanner();this.m.pan.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,Y(this,this.m.pan,a,c,d)}}};
self.ye=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.m=X(this);this.m.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=X(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.m.gain);this.C.start(0)}l(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;Y(this,this.m.gain,1-a/2,c,d);Y(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.we=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.A=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Hb=X(this);this.Hb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Hb.gain);this.C.start(0);this.A.connect(this.Hb);this.A.connect(this.h);this.Hb.connect(this.i)}l(){this.C.stop(0);this.C.disconnect();this.Hb.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.re=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.A=X(this);this.lc=X(this);this.kc=X(this);b=d;.01>b&&(b=.01);this.lc.gain.value=b;this.kc.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.oc=this.g.createWaveShaper();this.Qc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Qc[32768+e]=f,this.Qc[32768-
e-1]=-f;this.oc.curve=this.Qc;this.A.connect(this.lc);this.A.connect(this.h);this.lc.connect(this.oc);this.oc.connect(this.kc);this.kc.connect(this.i)}l(){this.A.disconnect();this.lc.disconnect();this.oc.disconnect();this.kc.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.oe=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};
self.ne=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.Sd=new Float32Array(this.m.frequencyBinCount);this.ge=new Uint8Array(a);this.ee=this.cb=0;b=this.v;b.Ua.add(this);T(b)}l(){this.v.Ua.delete(this);this.m.disconnect();super.l()}Sa(){this.m.getFloatFrequencyData(this.Sd);this.m.getByteTimeDomainData(this.ge);const b=this.m.fftSize;let a=this.cb=0;for(var c=0;c<b;++c){let d=(this.ge[c]-
128)/128;0>d&&(d=-d);this.cb<d&&(this.cb=d);a+=d*d}c=self.jb.Je;this.cb=c(this.cb);this.ee=c(Math.sqrt(a/b))}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};"use strict";function Ub(b){return new Promise((a,c)=>{b.getInsetTop(a,c)})}function Vb(b){return new Promise((a,c)=>{b.getInsetRight(a,c)})}function Wb(b){return new Promise((a,c)=>{b.getInsetBottom(a,c)})}function Xb(b){return new Promise((a,c)=>{b.getInsetLeft(a,c)})}
async function Yb(b){if(!b.Na)try{b.Na=await navigator.wakeLock.request("screen"),b.Na.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.Na=null;m(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),m(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),m(b,"wake-lock-error")}}
async function Zb(b){const a=await $b();m(b,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:a})}
async function $b(){var b=self.AndroidNotch;if(b)try{return await Promise.all([Ub(b),Vb(b),Wb(b),Xb(b)])}catch(c){return console.error("[Construct] Failed to get Android safe area inset: ",c),[0,0,0,0]}else{var a=document.body;b=a.style;b.setProperty("--temp-sai-top","env(safe-area-inset-top)");b.setProperty("--temp-sai-right","env(safe-area-inset-right)");b.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");b.setProperty("--temp-sai-left","env(safe-area-inset-left)");a=getComputedStyle(a);
a=[a.getPropertyValue("--temp-sai-top"),a.getPropertyValue("--temp-sai-right"),a.getPropertyValue("--temp-sai-bottom"),a.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);return isFinite(c)?c:0});b.removeProperty("--temp-sai-top");b.removeProperty("--temp-sai-right");b.removeProperty("--temp-sai-bottom");b.removeProperty("--temp-sai-left");return a}}
self.ga.Da(class extends self.wa{constructor(b){super(b,"platform-info");v(this,[["get-initial-state",()=>this.Kc()],["request-wake-lock",()=>Yb(this)],["release-wake-lock",()=>{this.Na&&(this.Na.release(),this.Na=null)}]]);window.addEventListener("resize",()=>Zb(this));this.Na=null}async Kc(){const b=await $b();return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:b,supportsWakeLock:!!navigator.wakeLock,isNwjs:"undefined"!==
typeof nw}}});
